services:
  postgres:
    image: postgres
    container_name: pinewood-derby-db
    environment:
      POSTGRES_USER: scout
      POSTGRES_PASSWORD: cubscoutsftw
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  pgdata: