export const parsedCsv = [
  {
    'Car Number': '1',
    'Car Name': '',
    Scout: 'Kelan Brandt',
    Den: '1',
    Superlative: "Cubmaster's Choice",
  },
  {
    'Car Number': '2',
    'Car Name': '',
    Scout: 'Kenneth Chan',
    Den: '1',
    Superlative: '',
  },
  {
    'Car Number': '3',
    'Car Name': '',
    Scout: 'Dominic Chan',
    Den: '3',
    Superlative: '',
  },
  {
    'Car Number': '4',
    'Car Name': '',
    Scout: 'Joon Oh Kwon',
    Den: '1',
    Superlative: '',
  },
  {
    'Car Number': '5',
    'Car Name': 'Mr. Tickles',
    Scout: 'James Boone',
    Den: '3',
    Superlative: 'Most Magical',
  },
  {
    'Car Number': '6',
    'Car Name': '',
    Scout: 'Lucas Liang',
    Den: '4',
    Superlative: '',
  },
  {
    'Car Number': '7',
    'Car Name': '',
    Scout: 'Ronan Hu',
    Den: '3',
    Superlative: 'Best Accessories',
  },
  {
    'Car Number': '8',
    'Car Name': '',
    Scout: 'Gabriel Boudrie',
    Den: '5',
    Superlative: 'Finest Craftsmanship',
  },
  {
    'Car Number': '9',
    'Car Name': '',
    Scout: 'Emma Boudrie',
    Den: '99',
    Superlative: '',
  },
  {
    'Car Number': '10',
    'Car Name': '',
    Scout: 'Greyson Boudrie',
    Den: '99',
    Superlative: '',
  },
  {
    'Car Number': '11',
    'Car Name': '',
    Scout: 'Devon Moss',
    Den: '8',
    Superlative: 'Wildest Design',
  },
  {
    'Car Number': '12',
    'Car Name': '',
    Scout: 'Advik Menon',
    Den: '5',
    Superlative: '',
  },
  {
    'Car Number': '13',
    'Car Name': '',
    Scout: 'Nicholas Lam',
    Den: '1',
    Superlative: 'Futuristic',
  },
  {
    'Car Number': '14',
    'Car Name': '',
    Scout: 'Eliot Glover',
    Den: '8',
    Superlative: '',
  },
  {
    'Car Number': '15',
    'Car Name': '',
    Scout: 'Maxwell Kelsey',
    Den: '3',
    Superlative: 'Best Dressed',
  },
  {
    'Car Number': '16',
    'Car Name': '',
    Scout: 'Nakoa Kelsey',
    Den: '1',
    Superlative: 'Creativity',
  },
  {
    'Car Number': '17',
    'Car Name': '',
    Scout: 'Lucas Lang',
    Den: '3',
    Superlative: 'Hot Rod',
  },
  {
    'Car Number': '18',
    'Car Name': '',
    Scout: 'Connor Namek',
    Den: '5',
    Superlative: 'Best Sports Theme',
  },
  {
    'Car Number': '19',
    'Car Name': '',
    Scout: 'Ethan Lang',
    Den: '99',
    Superlative: '',
  },
  {
    'Car Number': '20',
    'Car Name': '',
    Scout: 'Seneth Hewavitharana',
    Den: '8',
    Superlative: '',
  },
  {
    'Car Number': '21',
    'Car Name': '',
    Scout: 'Xander Afshar',
    Den: '4',
    Superlative: '',
  },
  {
    'Car Number': '22',
    'Car Name': '',
    Scout: 'Jerome So',
    Den: '8',
    Superlative: '',
  },
  {
    'Car Number': '23',
    'Car Name': '',
    Scout: 'Jon Louie',
    Den: '3',
    Superlative: '',
  },
  {
    'Car Number': '24',
    'Car Name': '',
    Scout: 'Lincoln Mattimoe',
    Den: '1',
    Superlative: 'Coolest Shape',
  },
  {
    'Car Number': '25',
    'Car Name': '',
    Scout: 'Xander Bowes',
    Den: '5',
    Superlative: 'Most Scholastic',
  },
  {
    'Car Number': '26',
    'Car Name': '',
    Scout: 'Joshua Hwang',
    Den: '3',
    Superlative: '',
  },
  {
    'Car Number': '27',
    'Car Name': '',
    Scout: 'Ian Go',
    Den: '5',
    Superlative: 'Mother Nature',
  },
  {
    'Car Number': '28',
    'Car Name': '',
    Scout: 'Bryce Gruhl',
    Den: '1',
    Superlative: 'Top Food',
  },
  {
    'Car Number': '29',
    'Car Name': '',
    Scout: 'Avery Abuda',
    Den: '8',
    Superlative: 'Best Mix of Colors',
  },
  {
    'Car Number': '30',
    'Car Name': '',
    Scout: 'Christopher Leong',
    Den: '8',
    Superlative: 'Most Artistic',
  },
  {
    'Car Number': '31',
    'Car Name': '',
    Scout: 'Cameron Petro',
    Den: '3',
    Superlative: '',
  },
  {
    'Car Number': '32',
    'Car Name': '',
    Scout: 'Lyla Ng.Rajah',
    Den: '3',
    Superlative: '',
  },
  {
    'Car Number': '33',
    'Car Name': '',
    Scout: 'Soomin Han',
    Den: '4',
    Superlative: 'Most Colorful',
  },
  {
    'Car Number': '34',
    'Car Name': '',
    Scout: 'Jaemin Han',
    Den: '1',
    Superlative: 'Out of this World',
  },
  {
    'Car Number': '35',
    'Car Name': '',
    Scout: 'Luca Francis',
    Den: '1',
    Superlative: 'Best Animal',
  },
  {
    'Car Number': '36',
    'Car Name': '',
    Scout: 'Emilia Francis',
    Den: '99',
    Superlative: '',
  },
  {
    'Car Number': '37',
    'Car Name': '',
    Scout: 'Arjun Pogde',
    Den: '1',
    Superlative: '',
  },
  {
    'Car Number': '38',
    'Car Name': '',
    Scout: 'Ella Conway',
    Den: '99',
    Superlative: '',
  },
  {
    'Car Number': '39',
    'Car Name': '',
    Scout: 'Ethan Conway',
    Den: '1',
    Superlative: 'Best Gamer',
  },
  {
    'Car Number': '40',
    'Car Name': '',
    Scout: 'William Conway',
    Den: '4',
    Superlative: 'Best California Cool',
  },
  {
    'Car Number': '41',
    'Car Name': '',
    Scout: 'Davis Dries',
    Den: '4',
    Superlative: 'Sportiest Design',
  },
  {
    'Car Number': '42',
    'Car Name': '',
    Scout: 'Juliette Bui',
    Den: '8',
    Superlative: '',
  },
  {
    'Car Number': '43',
    'Car Name': '',
    Scout: 'Paxton Bui',
    Den: '3',
    Superlative: '',
  },
];

export const mappedCsv = [
  {
    carNumber: 1,
    carName: null,
    owner: 'Kelan Brandt',
    denNumber: 1,
    superlative: "Cubmaster's Choice",
  },
  {
    carNumber: 2,
    carName: null,
    owner: 'Kenneth Chan',
    denNumber: 1,
    superlative: null,
  },
  {
    carNumber: 3,
    carName: null,
    owner: 'Dominic Chan',
    denNumber: 3,
    superlative: null,
  },
  {
    carNumber: 4,
    carName: null,
    owner: 'Joon Oh Kwon',
    denNumber: 1,
    superlative: null,
  },
  {
    carNumber: 5,
    carName: 'Mr. Tickles',
    owner: 'James Boone',
    denNumber: 3,
    superlative: 'Most Magical',
  },
  {
    carNumber: 6,
    carName: null,
    owner: 'Lucas Liang',
    denNumber: 4,
    superlative: null,
  },
  {
    carNumber: 7,
    carName: null,
    owner: 'Ronan Hu',
    denNumber: 3,
    superlative: 'Best Accessories',
  },
  {
    carNumber: 8,
    carName: null,
    owner: 'Gabriel Boudrie',
    denNumber: 5,
    superlative: 'Finest Craftsmanship',
  },
  {
    carNumber: 9,
    carName: null,
    owner: 'Emma Boudrie',
    denNumber: 99,
    superlative: null,
  },
  {
    carNumber: 10,
    carName: null,
    owner: 'Greyson Boudrie',
    denNumber: 99,
    superlative: null,
  },
  {
    carNumber: 11,
    carName: null,
    owner: 'Devon Moss',
    denNumber: 8,
    superlative: 'Wildest Design',
  },
  {
    carNumber: 12,
    carName: null,
    owner: 'Advik Menon',
    denNumber: 5,
    superlative: null,
  },
  {
    carNumber: 13,
    carName: null,
    owner: 'Nicholas Lam',
    denNumber: 1,
    superlative: 'Futuristic',
  },
  {
    carNumber: 14,
    carName: null,
    owner: 'Eliot Glover',
    denNumber: 8,
    superlative: null,
  },
  {
    carNumber: 15,
    carName: null,
    owner: 'Maxwell Kelsey',
    denNumber: 3,
    superlative: 'Best Dressed',
  },
  {
    carNumber: 16,
    carName: null,
    owner: 'Nakoa Kelsey',
    denNumber: 1,
    superlative: 'Creativity',
  },
  {
    carNumber: 17,
    carName: null,
    owner: 'Lucas Lang',
    denNumber: 3,
    superlative: 'Hot Rod',
  },
  {
    carNumber: 18,
    carName: null,
    owner: 'Connor Namek',
    denNumber: 5,
    superlative: 'Best Sports Theme',
  },
  {
    carNumber: 19,
    carName: null,
    owner: 'Ethan Lang',
    denNumber: 99,
    superlative: null,
  },
  {
    carNumber: 20,
    carName: null,
    owner: 'Seneth Hewavitharana',
    denNumber: 8,
    superlative: null,
  },
  {
    carNumber: 21,
    carName: null,
    owner: 'Xander Afshar',
    denNumber: 4,
    superlative: null,
  },
  {
    carNumber: 22,
    carName: null,
    owner: 'Jerome So',
    denNumber: 8,
    superlative: null,
  },
  {
    carNumber: 23,
    carName: null,
    owner: 'Jon Louie',
    denNumber: 3,
    superlative: null,
  },
  {
    carNumber: 24,
    carName: null,
    owner: 'Lincoln Mattimoe',
    denNumber: 1,
    superlative: 'Coolest Shape',
  },
  {
    carNumber: 25,
    carName: null,
    owner: 'Xander Bowes',
    denNumber: 5,
    superlative: 'Most Scholastic',
  },
  {
    carNumber: 26,
    carName: null,
    owner: 'Joshua Hwang',
    denNumber: 3,
    superlative: null,
  },
  {
    carNumber: 27,
    carName: null,
    owner: 'Ian Go',
    denNumber: 5,
    superlative: 'Mother Nature',
  },
  {
    carNumber: 28,
    carName: null,
    owner: 'Bryce Gruhl',
    denNumber: 1,
    superlative: 'Top Food',
  },
  {
    carNumber: 29,
    carName: null,
    owner: 'Avery Abuda',
    denNumber: 8,
    superlative: 'Best Mix of Colors',
  },
  {
    carNumber: 30,
    carName: null,
    owner: 'Christopher Leong',
    denNumber: 8,
    superlative: 'Most Artistic',
  },
  {
    carNumber: 31,
    carName: null,
    owner: 'Cameron Petro',
    denNumber: 3,
    superlative: null,
  },
  {
    carNumber: 32,
    carName: null,
    owner: 'Lyla Ng.Rajah',
    denNumber: 3,
    superlative: null,
  },
  {
    carNumber: 33,
    carName: null,
    owner: 'Soomin Han',
    denNumber: 4,
    superlative: 'Most Colorful',
  },
  {
    carNumber: 34,
    carName: null,
    owner: 'Jaemin Han',
    denNumber: 1,
    superlative: 'Out of this World',
  },
  {
    carNumber: 35,
    carName: null,
    owner: 'Luca Francis',
    denNumber: 1,
    superlative: 'Best Animal',
  },
  {
    carNumber: 36,
    carName: null,
    owner: 'Emilia Francis',
    denNumber: 99,
    superlative: null,
  },
  {
    carNumber: 37,
    carName: null,
    owner: 'Arjun Pogde',
    denNumber: 1,
    superlative: null,
  },
  {
    carNumber: 38,
    carName: null,
    owner: 'Ella Conway',
    denNumber: 99,
    superlative: null,
  },
  {
    carNumber: 39,
    carName: null,
    owner: 'Ethan Conway',
    denNumber: 1,
    superlative: 'Best Gamer',
  },
  {
    carNumber: 40,
    carName: null,
    owner: 'William Conway',
    denNumber: 4,
    superlative: 'Best California Cool',
  },
  {
    carNumber: 41,
    carName: null,
    owner: 'Davis Dries',
    denNumber: 4,
    superlative: 'Sportiest Design',
  },
  {
    carNumber: 42,
    carName: null,
    owner: 'Juliette Bui',
    denNumber: 8,
    superlative: null,
  },
  {
    carNumber: 43,
    carName: null,
    owner: 'Paxton Bui',
    denNumber: 3,
    superlative: null,
  },
];
